### ISSUE TITLE
Windows Batch File startup not working (except the fortiusant (exe))

### ISSUE THREAD

**Issue by msjnaessens** [WouterJD/FortiusANT#116]
Hey Wouter, I was still running an older version of fortiusant which did not include the startup batch files (such as manual power, manual grade, etc.) until you fixed the runoff function. Although I run fortiusant.py with my own startup batch file, I wanted to test yours. Unfortunately my system is unable to run these files (ModuleNotFoundError: No mudule named 'numpy'). Below is the Batch file for "gui, autostart, manual power" given which was included in the download and the error I get in cmd.
![run commands](https://user-images.githubusercontent.com/68154269/96296134-104cc880-0fef-11eb-85d7-a852067451cb.PNG)

When changed to my startup file format, I am able to execute the fortiusant.py file (no Tacx trainer connected at the moment).
![run commands changed](https://user-images.githubusercontent.com/68154269/96296276-50ac4680-0fef-11eb-80a2-dd6aa95286bc.PNG)

Is this a common problem, or is it just related to my system? Could you please explain why this is happening?

**Comment by WouterJD** [comment]
One difference between the two ways to startup is the "current directory".
When FortiusANT writes logfiles, those will be written in the StartUp folder in my case, and in the pythoncode folder in your case.

Then, I execute the .py and rely on the bindings in windows how to start a .py; which is defined in the registry (file associations),
You start python explicitly and that must be found in the PATH.

python will look for numpy and the two startup methods evidently have a slight difference, causing numpy not to be found.
I do not know why.

Interesting to find out, to become a real python / environment / installation specialist.
Always curious to hear what the cause was.
Thanks for updating me
