### ISSUE TITLE
i-Magic Problem

### ISSUE THREAD

**Issue by kiwisibk** [WouterJD/FortiusANT#148]
Hello,

I followed everything from the tutorial, the VR-interface looks installed fine.

![image](https://user-images.githubusercontent.com/32066779/99794421-6c44c880-2b2a-11eb-80f3-c605486182c0.png)

But FortiusANT is still not recognizing my interface/tainer... :(

![image](https://user-images.githubusercontent.com/32066779/99794362-5505db00-2b2a-11eb-9f5e-2a6ab43bfd84.png)

What I'm doing wrong??

Many thanks for any help!!

BR
Arno

**Comment by cyclingflow** [comment]
Wrong driver type. Your VR driver should be listed under libusb32-win devices. 

You probably will have to uninstall this driver (also select removing driver to be shure). (However, your tacx software will no longer work)

TIP: there are detailed instruction somewhere, i forgot. 
But if you download the libusb drivers and unpack, there will be a tool in the BIN folder called inf-wizard.exe.
Use it to make a custom ".inf" file for your vr-device, that allows you to provide a name ("VR-interface") such that it is listed
as "VR-device" under linusn-win32 in your device manager.

Otherwise, it will be listed as USb stick, leaving you with 3 such devices; confusing.

**Comment by cyclingflow** [comment]
And you might want to download my FortiusAnt version from my fork. See issue 143.

**Comment by kiwisibk** [comment]
That was exactly the issue! Thank you so much! Works like a charm now! Great 😊👍

**Comment by WouterJD** [comment]
@kiwisibk hi; please leave a note how I can improve the instructions in the manual
Thanks!

**Comment by kiwisibk** [comment]
Good point! Just add a tutorial how to enable unsigned drivers on Windows
10. And then, the process is following: connect the i-magic interface, go
to device manager, find the i-magic interface (almost on the top
highlighted with an erroneous driver), click on update driver, select
locate on hard drive, and select the folder where you firstly created the
.inf usblib driver you already are describing in your tutorial.

Thats it! 👍

Thanks once again for your outstanding work!! 😊

BR
Arno

P.S. if you want to send me a Word file of your tutorial I can edit it for
you and send it back for approval!


Wouter Dubbeldam <notifications@github.com> schrieb am Fr., 20. Nov. 2020,
21:57:

**Comment by switchabl** [comment]
@kiwisibk It should not normally be necessary to install unsigned drivers. Did Zadig not work for you?

In general, I think using Zadig (https://zadig.akeo.ie/) should be the recommended way to install libusb-win32 drivers (it is for many other projects that use libusb). It comes with signed drivers, generally just works with a couple of clicks and doesn't require creating custom .inf files either (well, it does create them, but it all happens automatically in the background). It also has the option to replace the Tacx drivers directly.

The only thing to be careful about is selecting the proper driver ("libusb-win32"), because it does other libusb flavours as well.

**Comment by cyclingflow** [comment]
Good point. Did not get around to using it before. But does work like a charm.
