### ISSUE TITLE
Follow up to #111, perhaps document solution

### ISSUE THREAD

**Issue by BrRoBo** [WouterJD/FortiusANT#155]
re: "GetTrainer - Unable to load firmware" on 1942 head unit #111

I seem to have had the exact same issue as "bradyap", but found a quick solution to my case.  Brady's screenshots of his issue are identical to what I was seeing and we had the same head unit... T1942.  The install is on a clean version of Windows 10 64bit, no prior TTS or other Tacx software installed.

What I think happens is that we do the lib USB driver install and successfully see the Fortius unit listed under libusb-win32 devices in Device Manager along with how-ever-many Ant USB stick 2 are connected.  Then when we run the FortiusAnt.exe application, it seems to be looking for a different device or registration, and causes the Fortius to unload from the list of "libusb-win32 devices" and then there is a new "Tacx Fortius" listed under "Other devices".  This unregistration, re-registration cycle is reproducible over and over by disconnecting the Fortius USB, then plug it in to load the lib32 driver and see it properly listed, then use the FortiusAnt "Locate HW" which again will cause the Fortius to get re-registered under "Other devices".

The simple solution at this point is to drill down in Device Manager->Other Devices and open the properties for the "Tacx Fortius" listed under "Other devices".  Then "Update drivers", select "libusb-win32 devices", then "Tacx", then select whatever name you used ("VR-Interface", "Fortius Virtual Trainer", etc.  FWIW, I used the latter "Fortius Virtual Trainer" as my device name).  Bingo, the Fortius head unit is reloaded into the correct list of "libusb-win32 devices".  Issue fixed for this USB port.  If the Fortius USB plug is moved to a different port, this library/device driver fix must be performed once per each port to correct the issue, and then will no longer occur if the Fortius USB plug is moved around to different ports.

I'm not sure if this is a rare corner case or if it actually happens more than people report here.

Anyway, thanks for putting this together!  I tried a different solution some years ago (and still had one Suunto ANT mini from that attempt) but had put this to rest until just recently finding your better FortiusAnt solution.

**Comment by WouterJD** [comment]
added to manual

**Comment by PeterKassenaar** [comment]
Hi @BrRoBo,

While installing FortiusAnt, I just ran into this problem ("Unable to load firmware"). The Tacx Trainer in my case was also unregistered in the libusb-win32 devices tree and then re-registered in the Other Devices tree. So I was also stuck in this cycle.

Using your suggestions, I was able to solve it. Thanks! 

However, it looks like you missed one (important) point, after the "Update drivers" step. You'll also have to choose "Let me pick from a list of available drivers on my computer" in the next step, otherwise you'll never see the "libusb-win32"  option.

For clarity I made screenshots of the complete process, hopefully other people that also run into this cycle can benefit.

1.  Tacx Fortius was first correctly installed, but after starting FortiusANt re-registered as Unknown Device.
![image](https://user-images.githubusercontent.com/582349/104762530-d1045400-5764-11eb-9a93-5406621438d6.png)

2. Rightclick, then "Update Drivers". Select "Let me pick from a list..." in the next screen (this step was omitted in the solution above).

![image](https://user-images.githubusercontent.com/582349/104762698-14f75900-5765-11eb-84ee-3d68b3536d28.png)

3. Select category "libusb-win32 devices"

![image](https://user-images.githubusercontent.com/582349/104762841-4d973280-5765-11eb-87bb-2cf4fe1d18f4.png)

4. Select Tacx, Tacx Fortius (or whatever you called your trainer) and then Next.

![image](https://user-images.githubusercontent.com/582349/104762901-69023d80-5765-11eb-8c1d-f15eada73c76.png)

5. Click "Yes" in the Update Driver Warning dialog box.

![image](https://user-images.githubusercontent.com/582349/104762942-7c150d80-5765-11eb-9d1f-24d336db6f3c.png)

6. After that, the device should be working properly. Click Close.

![image](https://user-images.githubusercontent.com/582349/104763012-964eeb80-5765-11eb-9b7e-78b56474aec6.png)

7. Tacx is now listed in the correct category. You can start FortiusAnt and should NOT get the "Unable to load firmware" message anymore. However, repeat this process for every USB-port that you connect the Tacx to.

![image](https://user-images.githubusercontent.com/582349/104763157-c5fdf380-5765-11eb-8dfd-4a1c2fc60f19.png)

**Comment by switchabl** [comment]
This should not be necessary anymore if you use the all-in-one driver package (https://github.com/switchabl/FortiusANT/releases/download/v4.0/libusb-win32_T19xx.exe, #168).

**Comment by WouterJD** [comment]
Agree, and is now documented in manual
