### ISSUE TITLE
Problem connecting Fortius T1942 to FortiusAnt

### ISSUE THREAD

**Issue by yancart** [WouterJD/FortiusANT#289]
Hi, Ive now bought two genuine Garmin USB Ant+ dongles and I'm still having issues connecting to the Tacx T1942.

So my USB ports are setup as follows, does this look ok?
![image](https://user-images.githubusercontent.com/64601681/112224935-f1003a00-8c23-11eb-8272-7f922bc20934.png)

and when I start FortiusAnt I get the following:-
![image](https://user-images.githubusercontent.com/64601681/112224835-cd3cf400-8c23-11eb-98b7-3999238f0dad.png)

Is there anything that doesnt right?
Thanks

**Comment by WouterJD** [comment]
Connecting the tacx is not related to ANT.
Did you follow instructions in manual?

**Comment by yancart** [comment]
Yes followed the instructions.
Last week the Tax and CYCPLUS dongles were connecting but I was getting dropouts in the connection to Zwift.
I have now just changed the dongles to genuine Garmin ANT+ dongles, which as you say say shouldnt affect the Tacx connection as this is just a wired a USB link?
Assume the Fortius_Unint/Windriver1230 driver setup is correct?
Thanks

**Comment by WouterJD** [comment]
Do you still get the same message "No Tacx USB trainer found"?
That is NOT related to the ANT+dongles.

I cannot verify whether the T1942 setup is correct because I do not have that headunit.

Recommended:
- Use a clean PC without Tacx software
- Follow manual 3.6.1	Windows – prepackaged drivers

FortiusAnt will detect the uninitialized headunit, load the software and then detect the T1942
See also 5.8.1	Unable to load firmware" on 1942 head unit

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
