### ISSUE TITLE
ANT+ can't connect to both FortiusANT software and Rouvy at the same time

### ISSUE THREAD

**Issue by RodeTheAlpe** [WouterJD/FortiusANT#331]
This is the first time I've seen this issue.  Running 6.2 on Windows 10.  Head unit T1942

FortiusAnt runs fine but when I start Rouvy it doesn't see any of the ANT devices.  If I quit FortiusANT then Rouvy sees the ANT devices but then FortiusAnt cant see them.

I've uninstalled and reinstalled both pieces of software with no luck.  I may try going back to v5.1 if I have time and seeing if that still works.

**Comment by WouterJD** [comment]
FortiusAnt connects to one ANT device only, if the other one (I assume you have two ANT dongles in your PC) is not found by rouvy I suspect a third piece of software to be present.
Garmin Express would be a good candidate

**Comment by RodeTheAlpe** [comment]
No Garmin Express or anything new except updating to 6.2 yesterday.  
If you can take a look at the screen shot and let me know which id is the one that FortiusAnt is connecting to and which one Rouvy should be looking for I'll double check that Rouvy not trying to connect to the wrong ANT device.
Thanks
![Capture](https://user-images.githubusercontent.com/46135033/141172800-e06eb177-1996-4a1b-a135-277b541f3e44.JPG)
!

**Comment by WouterJD** [comment]
Assuming you have two ANT-dongles in your PC
FortiusAnt uses one dongle, connects to your trainer and broadcasts data.

When Rouvy is started, it should connect to the second dongle and should see the devices as listed.

Programs like FortiusAnt and Rouvy search for a free ANT dongle and take the first one found available.

**Comment by RodeTheAlpe** [comment]
Yes two dongles.  Rouvy let's you choose which device.  I'm guessing at some point FortiusANT grabbed the second one and both pieces of software were fighting it out.  I reset the dongles and switched the one Rouvy was looking at and it seems to have fixed the problem.  Wonder if there is a way to force FortiusANT to grab a specific device?

**Comment by WouterJD** [comment]
See section 4.2 

-D value	Select one specific antDongle (perhaps with a non-standard deviceID). The following types are known: 4104 = Suunto, 4105 = Garmin, 4100 = Older. -1 means: no ANT.

This works if you have two different ANT-dongles; the deviceID is to filter USB devices.

If NOT, remove one ANT-dongle; start FortiusANT which will use the inserted ANTdongle.
The insert the second ANT-dongle and start Rouvy.
Not something you will want to do regularly, but at least to debug the situation.

PS. "and both pieces of software were fighting it out" seems odd because:
FortiusANT (and I assume other software as well) enumerates ANT-dongles and tries to connect. If in-use, proceed with next untill a free dongle is found. If Rouvy is not yet started, FortiusAnt takes the first dongle in the enumeration-list.

The Rouvy willl do the same (assumption), detect that the first is in-use and use the second.

**Comment by RodeTheAlpe** [comment]
Seems stable now that each piece of software has found what it was looking for.  Wonder if one of the two ANT dongles was glitching out.  Anyway, all good now.  Thanks again for your insight, feel free to remove this issue.
