### ISSUE TITLE
Cadence from FortiusAnt

### ISSUE THREAD

**Issue by Toetta** [WouterJD/FortiusANT#377]
Running Zwift ant FortiusANT with iVortex trainer the cadence is showing. Where from is this input generated having no cranksensor?

**Comment by WouterJD** [comment]
The Vortex provides Power, Speed and Cadence through ANT-messages as received by FortiusAnt.
Power and Speed are "obvious" and measured on the wheel.

When cycling, the provided power is not regular at each pedal-position; advanced trainers show the Pedal-Stroke analysis so you can see where your max/min power is and how the balamce right/left is. (This is also implemented in FortiusAnt graphical use interface).

If a trainer not only measures the power but also detects the variation in power while riding, the cadence can be concluded.
I ASSUME that such is the case, since I have no knowledge on the internals of the Vortex and/or the Tacx software inside.

I hope this is satisfactory for you; please let me know whether this makes sense for you and whether the cadence is correct
