### ISSUE TITLE
UserGuide unreadable

### ISSUE THREAD

**Issue by MaxiPalle** [WouterJD/FortiusANT#397]
I'd like to use a Tacx Vortex T1961 with FortiusANT as described in #261.

Before starting with the implementation, I would like to know how to proceed ;-) but cannot read the corresponding UserGuide (Unable to render code block). Am I the onl one with this problem?

**Comment by WouterJD** [comment]
Hi @MaxiPalle
Please share the unreadable page, I will check

**Comment by MaxiPalle** [comment]
Hi Wouter,

it is https://github.com/WouterJD/FortiusANT/blob/master/doc/FortiusANTUserManual.pdf

Thank you!

**Comment by WouterJD** [comment]
I understand that, but what page is unreadable?
Screenshot...

**Comment by MaxiPalle** [comment]
This is, how it looks, if you click the file. I'd expect to open and show it.

![image](https://user-images.githubusercontent.com/19306466/199187325-1fae88bd-b0e3-4c91-8fb1-46858132ea04.png)

But as downloading and opening the file is possible on my local machine, there is no real problem ;-)

**Comment by WouterJD** [comment]
In my browser it's as below.
It seems you have a (PDF plugin in the) browser that gives the error, which is not a FortiusAnt issue but more a browser issue; especially because a downloaded PDF can be read on your system.
Success in further investigation!

![image](https://user-images.githubusercontent.com/47486941/199187928-70daee07-5fc9-4a39-96a2-7ad3c9b0189f.png)
