### ISSUE TITLE
Tacx genius not found

### ISSUE THREAD

**Issue by jobruiter** [WouterJD/FortiusANT#449]
Hi,

I am in the following situation:
I have a Tacx Genius (srnr: 211101565) that i want to connect with Zwift through FortiusANT with an ANT+ dongle.
FortiusANT does recognize the ANT dongle, but doesnt find a tacx trainer. As you can see in the screenshot underneath.

Question:
How can i connect the tacx trainer to FortiusANT to Zwift. On one laptop and one ANT dongle.

If more information is needed to help me, please ask me. I am quite new to this software and tacx.

Thank you in advance! I need to get in shape this winter ;)

![image](https://github.com/WouterJD/FortiusANT/assets/153859947/3ba2740e-5dc1-49c9-84dc-a817d31be90c)

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -

To connect to a Genius, you need an ANT-dongle for FortiusAnt.
As you can see in the second message, the ANT-dongle is not available; most likely because other software has attached to it.

Note that you need a dongle per program: Zwift, FortiusAnt, Garmin connect, ...

For a starter: how many dongle do you have (1) and what other software is running (2).
Watch out for Garmin Express, which keeps running in background

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
