### ISSUE TITLE
Trainer not being found

### ISSUE THREAD

**Issue by aepeaky** [WouterJD/FortiusANT#467]
I've been trying to connect my tacx genius t2021 trainer for a quite a while. I purchased an ant+ usb but i have not been able to connect it to my laptop since.![image](https://github.com/user-attachments/assets/5f64161f-a017-4f57-898a-fb975f89e17f)![image](https://github.com/user-attachments/assets/71697c7b-afd8-4229-bdfd-a7a27d5e26c3)![image](https://github.com/user-attachments/assets/164e9de3-43cc-4d4a-a905-8471c9e1d659)

**Comment by WouterJD** [comment]
Welcome to the FortiusANT community
- - -
I'm always curious to know who I communicate with, where FortiusANT is used and what configuration is used.
Please tell me what bundle did you buy, and what brake and what head unit do you use?
I would therefore appreciate that you introduce yourself; perhaps leave a comment under issue #14.
You could also consider to visit [the sponsor page](https://github.com/sponsors/WouterJD)
- - -


I read you have  tacx Genius 2021. Is that with a USB-connected headunit (since you are installing the USB driver)?

In that case:
- FortiusAnt should find it and connect to it using the USB interface.
- FortiusAnt will publish itself on the USB ANT dongle to communicate with, let's say Zwift. If the ANT dongle is in use, check for other applications like Garmin Connect or Zwift on your PC. If you want to run FortiusAnt AND Zwift on the same system, you need two dongles.

First things first, let's get the trainer connected.

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
