### ISSUE TITLE
working with powermeter

### ISSUE THREAD

**Issue by fitty77** [WouterJD/FortiusANT#69]
Hello

Congrats on the great work

Have some questions about this. If i run FortiusANT, and a powermeter (so i can have correct power numbers, and specially, simply because i have one), will i have any issues? I mean, is Zwift, when starting there is this possibility. Don't know if it will work correctly. Also, as my powermeter is on crank spider, i also have cadence available through it, as well as hrm sensor. So, what i'm saying is that i only want FortiusANT, to control the trainer. I don't want any other feedback from it, as i can give that to Zwift through individual sensors. So, is all this possible?

Thanks

**Comment by WouterJD** [comment]
Zwift is so friendly to let you chose devices, even if they are one ANT+ FE-C trainer.

So you can connect to FortiusANT to CONTROL the trainer and connect to the Powermeter to READ the actual values.


What I have also done is READ the actual values from FortiusANT (so I'm moving over the Zwift world) and CONTROL FortiusANT from Trainer Road which has structured trainings.

It's a bit of experimenting!

@fitty77 welcome onboard and since I'm always interested where the FortiusANT users come from, planting a flag on the FortiusANT world - please sign the #14 page and/or say hello on Strava! https://www.strava.com/athletes/2885978
