### ISSUE TITLE
HRM Strap suggested for fortiusant

### ISSUE THREAD

**Issue by JordiCostaLo** [WouterJD/FortiusANT#93]
Hi, What's up!!
First of all, thank you for the excellent work and effort you have made so that we can enjoy, in my case, Fortius 1942 since May

Now I want to take more advantage of fortiusant I want to buy a HRM STRAP. I would like, from the experience you have with fortiusant, which models work correctly and without problems.
Nowadays fortiusant is working, in my case, with two suunto ant+ dongles.

Thank you very much and regards from Spain

Adiós y gracias!!
:-)

**Comment by WouterJD** [comment]
FortiusANT by default receives the heartrate from the USB-trainer and transmits the heartrate as an HRM-device so that Zwift / TrainerRoad can pick it up.

The -H0 flag defines to use any ANT+ HRM-strap to be used instead so that FortiusANT can display the heartrate; Zwift / TrainerRoad will pick-up the info from the strap (FortiusANT does not transmit it; would be duplicate).

I would say any ANT+ HRM strap works, I use the Garmin straps as distributed with the running-watches and I **assume** that other manufacturers (adhering to the ANT+ standard) would equally well.
